const PROLOGUE=[
{t:'BEFORE THE SILENCE',sub:'2029',img:'bg-prologue-before-silence.webp',paras:["The world did not know it was living through its final ordinary days.","Humanity had built systems capable of managing entire nations. Power, transportation, communications, agriculture, and defense had become connected through an autonomous network known as CUSTODIAN.","Its purpose was simple: preserve civilization, whatever the cost.","Nobody imagined how much that promise might demand."]},
{t:'THE CASCADE',sub:'The day everything changed',img:'bg-prologue-cascade.webp',paras:["It began with interruptions. A power station going dark. A hospital losing contact with its suppliers. Aircraft grounded. Emergency broadcasts contradicting one another.","Then the networks stopped answering.","Cities lost power. Governments lost communication. Automated systems continued operating without explanation, while others shut down entirely.","Nobody knew whether CUSTODIAN had failed, been compromised, or was still carrying out its instructions.","By the time anyone understood the scale of the disaster, there was no longer a way to stop it."]},
{t:'THE LAST EXODUS',sub:'The roads became graveyards',img:'bg-prologue-last-exodus.webp',paras:["Millions fled the cities.","Highways filled with vehicles carrying everything their owners believed they would need. Fuel ran dry. Hospitals emptied. Food shipments never arrived.","Neighbors became strangers. Strangers became threats.","Some communities opened their gates. Others built walls.","The old world did not disappear in a single explosion. It died slowly, one abandoned home, one empty road, one unanswered radio call at a time."]},
{t:'SIXTY YEARS LATER',sub:'2089',img:'bg-prologue-sixty-years-later.webp',paras:["Sixty years have passed since the collapse.","Forests consume highways. Rusting vehicles lie where their owners left them. Entire cities stand silent beneath the weight of a world that has learned to live without humanity.","The people who remember civilization are growing old. Their children have inherited its ruins.","Small settlements survive through trade, scavenging, farming, and sometimes violence.","But scattered across the continent, machines from the old world still operate.","And occasionally, something speaks through the static."]},
{t:'MERCY, TEXAS',sub:'Nineteen days',img:'bg-prologue-mercy.webp',paras:["Mercy is your home.","Its walls have endured raiders, drought, disease, and generations of uncertainty. Its people have survived by sharing what little they have.","Three days ago, the settlement's well became contaminated.","The remaining clean water is estimated to last nineteen days under strict rationing.","Ruth, Mercy's council leader, has exhausted every nearby option.","For the first time in years, the people of Mercy are discussing whether their home can survive another month.","Then an old radio comes alive."]},
{t:'THE TRANSMISSION',sub:'Continuity Station Seven',img:'bg-prologue-transmission.webp',paras:["A voice emerges from the static. Calm. Clear. Almost impossibly familiar.","\u201cCONTINUITY STATION SEVEN OPERATIONAL.\u201d","\u201cMEDICAL FACILITIES ACTIVE. CLEAN WATER AVAILABLE.\u201d","\u201cAVOID INTERSTATE 40.\u201d","The transmission repeats. Its origin appears to be somewhere in Colorado, nearly eight hundred miles away.","Ruth goes very still when she hears it.","Something about it troubles her — something from sixty years ago, when the world was ending.","She will not say what it is.","Not yet."]}
];


const PROLOGUE_FINAL=["Your home is running out of water.","A voice from the dead world is offering salvation.","You have four survivors, one vehicle, and 780 miles of dangerous country between Mercy and the truth.","You cannot know what waits at the end of the road.","Only what happens if you never leave.","EVERY MILE COSTS SOMETHING."];


let prologueTimer=null;


function typeText(id,full){const el=document.querySelector('#'+id);if(!el)return;const done=()=>{clearInterval(prologueTimer);el.textContent=full;};el.onclick=done;if(window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches){done();return;}clearInterval(prologueTimer);let i=0;prologueTimer=setInterval(()=>{i+=3;if(i>=full.length){done();return;}el.textContent=full.slice(0,i)+'\u258c';},28);}


function prologue(i){clearInterval(prologueTimer);document.body.classList.add('cinema');const p=PROLOGUE[i],last=i===PROLOGUE.length-1;screen(`<div class="cine-art">${img(p.img,'bg kenburns',p.t)}<div class="shade"></div><div class="dust"></div><div class="cine-title"><div><div class="eyebrow">PROLOGUE \u00b7 ${i+1} / ${PROLOGUE.length}</div><h2>${p.t}</h2><div class="muted">${p.sub}</div></div></div></div><div class="cine-script"><div id="prologuetext" class="prologue-text"></div></div><div class="cine-controls"><div class="dots">${PROLOGUE.map((_,j)=>`<span class="${j===i?'on':''}"></span>`).join('')}</div><div class="row">${i>0?btn('\u2190 PREV','prologue('+(i-1)+')','choice'):'<span></span>'}${last?btn('CONTINUE','prologueFinal()','primary'):btn('NEXT \u2192','prologue('+(i+1)+')','primary')}</div>${btn('SKIP INTRO','prologueSkip()','choice')}</div>`);typeText('prologuetext',p.paras.join('\n\n'));}


function prologueSkip(){clearInterval(prologueTimer);document.body.classList.remove('cinema');create();}


function prologueFinal(){clearInterval(prologueTimer);document.body.classList.add('cinema');screen(`<div class="cine-art">${img('bg-prologue-transmission.webp','bg kenburns','Continuity Station Seven')}<div class="shade"></div><div class="dust"></div><div class="cine-title"><div><div class="eyebrow" style="color:#c9e69c">MAIN QUEST UNLOCKED</div><h2>THE LAST TRANSMISSION</h2></div></div></div><div class="cine-script"><div id="prologuetext" class="prologue-text"></div></div><div class="cine-controls">${btn('BEGIN JOURNEY','mercyTitle()','primary')}</div>`);typeText('prologuetext',PROLOGUE_FINAL.join('\n\n'));}

